#Training
train_q_table: 'snake_q_table_v4.npy'
train_env_size:
  width: 10
  height: 10
train_episodes: 1000000
max_steps: 1000000

learning_rate: 0.99
gamma: 0.9

max_epsilon: 1
min_epsilon: 0.1
decay_rate: 0.000005

#Evaluation
eval_q_table: 'snake_q_table_v3.npy'
valid_env_size:
  width: 10
  height: 10
eval_episodes: 100
eval_max_steps: 1000
display_game: true